name: primeira-pipeline
on: 
  push:
    branches: ["main"]
  workflow_dispatch: 

jobs:
  primeiro-job:
    name: "meu primeiro job"
    runs-on: ubuntu-latest
    steps:
      - name: "minha primeira ação"
        run: echo "hello world!"
      - name: "segunda ação"
        run: |
          echo "Você criou o seu primeiro workflow!!!"
          echo "Parabéns!"
      - name: "Script Python"
        run: |
          variavel = "Hello World!"
          print(variavel)
        shell: python
